-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "username" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "roleType" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "graduationYear" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "educationHistory" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "experienceHistory" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "skillsData" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "projectList" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "connectionsData" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sectionVisibility" JSONB;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "User_username_key" ON "User"("username");
