// Indian Colleges, Languages, Tech Stack & Computer Science Concepts Master Data

export const INDIAN_COLLEGES: string[] = [
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "Indian Institute of Technology Roorkee (IIT Roorkee)",
  "Indian Institute of Technology Guwahati (IIT Guwahati)",
  "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
  "Indian Institute of Technology (BHU) Varanasi",
  "Indian Institute of Technology (ISM) Dhanbad",
  "Indian Institute of Technology Indore (IIT Indore)",
  "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)",
  "Indian Institute of Technology Ropar (IIT Ropar)",
  "Indian Institute of Technology Patna (IIT Patna)",
  "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)",
  "Indian Institute of Technology Mandi (IIT Mandi)",
  "Indian Institute of Technology Jodhpur (IIT Jodhpur)",
  "Indian Institute of Technology Tirupati (IIT Tirupati)",
  "Indian Institute of Technology Bhilai (IIT Bhilai)",
  "Indian Institute of Technology Goa (IIT Goa)",
  "Indian Institute of Technology Jammu (IIT Jammu)",
  "Indian Institute of Technology Dharwad (IIT Dharwad)",
  "Indian Institute of Technology Palakkad (IIT Palakkad)",
  "National Institute of Technology Tiruchirappalli (NIT Trichy)",
  "National Institute of Technology Karnataka (NIT Surathkal)",
  "National Institute of Technology Rourkela (NIT Rourkela)",
  "National Institute of Technology Warangal (NIT Warangal)",
  "National Institute of Technology Calicut (NIT Calicut)",
  "Visvesvaraya National Institute of Technology (VNIT Nagpur)",
  "Malaviya National Institute of Technology (MNIT Jaipur)",
  "Motilal Nehru National Institute of Technology (MNNIT Allahabad)",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra)",
  "National Institute of Technology Durgapur (NIT Durgapur)",
  "National Institute of Technology Silchar (NIT Silchar)",
  "National Institute of Technology Jamshedpur (NIT Jamshedpur)",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT Surat)",
  "Maulana Azad National Institute of Technology (MANIT Bhopal)",
  "Dr. B R Ambedkar National Institute of Technology (NIT Jalandhar)",
  "National Institute of Technology Hamirpur (NIT Hamirpur)",
  "National Institute of Technology Patna (NIT Patna)",
  "National Institute of Technology Raipur (NIT Raipur)",
  "National Institute of Technology Goa (NIT Goa)",
  "National Institute of Technology Agartala (NIT Agartala)",
  "National Institute of Technology Meghalaya (NIT Meghalaya)",
  "National Institute of Technology Manipur (NIT Manipur)",
  "National Institute of Technology Nagaland (NIT Nagaland)",
  "National Institute of Technology Mizoram (NIT Mizoram)",
  "National Institute of Technology Arunachal Pradesh (NIT Arunachal)",
  "National Institute of Technology Sikkim (NIT Sikkim)",
  "National Institute of Technology Puducherry (NIT Puducherry)",
  "National Institute of Technology Uttarakhand (NIT Uttarakhand)",
  "National Institute of Technology Andhra Pradesh (NIT AP)",
  "National Institute of Technology Srinagar (NIT Srinagar)",
  "Indian Institute of Engineering Science and Technology (IIEST Shibpur)",
  "International Institute of Information Technology Hyderabad (IIIT Hyderabad)",
  "International Institute of Information Technology Bangalore (IIIT Bangalore)",
  "Indraprastha Institute of Information Technology Delhi (IIIT Delhi)",
  "Indian Institute of Information Technology Allahabad (IIIT Allahabad)",
  "ABV-Indian Institute of Information Technology and Management (IIITM Gwalior)",
  "Indian Institute of Information Technology, Design and Manufacturing (IIITDM Jabalpur)",
  "Indian Institute of Information Technology, Design and Manufacturing (IIITDM Kancheepuram)",
  "Indian Institute of Information Technology, Design and Manufacturing (IIITDM Kurnool)",
  "Indian Institute of Information Technology Lucknow (IIIT Lucknow)",
  "Indian Institute of Information Technology Pune (IIIT Pune)",
  "Indian Institute of Information Technology Sri City (IIIT Sri City)",
  "Indian Institute of Information Technology Vadodara (IIIT Vadodara)",
  "Indian Institute of Information Technology Kota (IIIT Kota)",
  "Indian Institute of Information Technology Guwahati (IIIT Guwahati)",
  "Indian Institute of Information Technology Kalyani (IIIT Kalyani)",
  "Indian Institute of Information Technology Sonepat (IIIT Sonepat)",
  "Indian Institute of Information Technology Una (IIIT Una)",
  "Indian Institute of Information Technology Surat (IIIT Surat)",
  "Indian Institute of Information Technology Bhopal (IIIT Bhopal)",
  "Indian Institute of Information Technology Bhagalpur (IIIT Bhagalpur)",
  "Indian Institute of Information Technology Agartala (IIIT Agartala)",
  "Indian Institute of Information Technology Raichur (IIIT Raichur)",
  "Indian Institute of Information Technology Dharwad (IIIT Dharwad)",
  "Indian Institute of Information Technology Kottayam (IIIT Kottayam)",
  "Indian Institute of Information Technology Manipur (IIIT Manipur)",
  "Indian Institute of Information Technology Ranchi (IIIT Ranchi)",
  "Birla Institute of Technology and Science, Pilani (BITS Pilani)",
  "Birla Institute of Technology and Science, Pilani - Goa Campus",
  "Birla Institute of Technology and Science, Pilani - Hyderabad Campus",
  "Indian Institute of Science (IISc Bangalore)",
  "Indian Statistical Institute (ISI Kolkata)",
  "Indian Statistical Institute (ISI Delhi)",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW)",
  "Jadavpur University, Kolkata",
  "College of Engineering, Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI Mumbai)",
  "Sardar Patel Institute of Technology (SPIT Mumbai)",
  "Pune Institute of Computer Technology (PICT Pune)",
  "Vishwakarma Institute of Technology (VIT Pune)",
  "Walchand College of Engineering, Sangli",
  "Anna University (CEG Guindy / MIT Chromepet), Chennai",
  "PSG College of Technology, Coimbatore",
  "Coimbatore Institute of Technology (CIT)",
  "Thiagarajar College of Engineering, Madurai",
  "SSN College of Engineering, Chennai",
  "SASTRA Deemed to be University, Thanjavur",
  "Amrita Vishwa Vidyapeetham (Coimbatore / Bengaluru / Amritapuri / Chennai)",
  "Vellore Institute of Technology (VIT Vellore)",
  "Vellore Institute of Technology (VIT Chennai)",
  "Vellore Institute of Technology (VIT Bhopal)",
  "Vellore Institute of Technology (VIT-AP University)",
  "SRM Institute of Science and Technology (SRM Kattankulathur)",
  "SRM Institute of Science and Technology (SRM Ramapuram / Vadapalani)",
  "SRM University-AP, Amaravati",
  "Manipal Institute of Technology (MIT Manipal)",
  "Manipal University Jaipur (MUJ)",
  "Thapar Institute of Engineering and Technology (TIET Patiala)",
  "Punjab Engineering College (PEC Chandigarh)",
  "Birla Institute of Technology, Mesra (BIT Mesra Ranchi)",
  "C.V. Raman Global University (CVRGU Bhubaneswar)",
  "Kalinga Institute of Industrial Technology (KIIT Bhubaneswar)",
  "Institute of Technical Education and Research (ITER / SOA University, Bhubaneswar)",
  "Silicon University / Silicon Institute of Technology, Bhubaneswar",
  "Odisha University of Technology and Research (OUTR / CET Bhubaneswar)",
  "Veer Surendra Sai University of Technology (VSSUT Burla)",
  "National Institute of Science and Technology (NIST Berhampur)",
  "Indira Gandhi Institute of Technology (IGIT Sarang)",
  "Government College of Engineering, Kalahandi (GCEK)",
  "Government College of Engineering, Keonjhar (GCEKJR)",
  "Parala Maharaja Engineering College (PMEC Berhampur)",
  "Ghanashyam Hemalata Institute of Technology and Management (GHITM Puri)",
  "Gandhi Institute for Technological Advancement (GITA Autonomous, Bhubaneswar)",
  "Gandhi Engineering College (GEC Bhubaneswar)",
  "Trident Academy of Technology (TAT Bhubaneswar)",
  "Hi-Tech College of Engineering, Bhubaneswar",
  "Centurion University of Technology and Management (CUTM Odisha)",
  "Utkal University, Bhubaneswar",
  "Ravenshaw University, Cuttack",
  "RV College of Engineering (RVCE Bangalore)",
  "BMS College of Engineering (BMSCE Bangalore)",
  "MS Ramaiah Institute of Technology (MSRIT Bangalore)",
  "PES University (Ring Road / Electronic City, Bangalore)",
  "Dayananda Sagar College of Engineering (DSCE Bangalore)",
  "Bangalore Institute of Technology (BIT Bangalore)",
  "Sir M. Visvesvaraya Institute of Technology (Sir MVIT Bangalore)",
  "Siddaganga Institute of Technology (SIT Tumkur)",
  "The National Institute of Engineering (NIE Mysore)",
  "University Visvesvaraya College of Engineering (UVCE Bangalore)",
  "JSS Science and Technology University (SJCE Mysore)",
  "KLE Technological University (BVBCET Hubli)",
  "BMS Institute of Technology and Management (BMSIT Bangalore)",
  "New Horizon College of Engineering (NHCE Bangalore)",
  "CMR Institute of Technology (CMRIT Bangalore)",
  "Nitte Meenakshi Institute of Technology (NMIT Bangalore)",
  "RNS Institute of Technology (RNSIT Bangalore)",
  "Reva University, Bangalore",
  "Christ University (Faculty of Engineering), Bangalore",
  "Maharaja Agrasen Institute of Technology (MAIT Delhi)",
  "Maharaja Surajmal Institute of Technology (MSIT Delhi)",
  "Bharati Vidyapeeth's College of Engineering (BVCOE New Delhi)",
  "Bhagwan Parshuram Institute of Technology (BPIT Delhi)",
  "University School of Information, Communication & Technology (USICT Delhi)",
  "Vivekananda Institute of Professional Studies (VIPS Delhi)",
  "University of Delhi (Cluster Innovation Centre / Faculty of Technology)",
  "Jamia Millia Islamia (Faculty of Engineering), New Delhi",
  "Jamia Hamdard, New Delhi",
  "Jawaharlal Nehru University (SEST), New Delhi",
  "Jaypee Institute of Information Technology (JIIT Noida)",
  "JSS Academy of Technical Education (JSS Noida)",
  "Ajay Kumar Garg Engineering College (AKGEC Ghaziabad)",
  "KIET Group of Institutions, Ghaziabad",
  "ABES Engineering College, Ghaziabad",
  "Galgotias College of Engineering and Technology (GCET Greater Noida)",
  "Galgotias University, Greater Noida",
  "GL Bajaj Institute of Technology and Management, Greater Noida",
  "Amity University, Noida",
  "Sharda University, Greater Noida",
  "Bennett University, Greater Noida",
  "Shiv Nadar University (SNU Greater Noida)",
  "The NorthCap University (NCU Gurugram)",
  "BML Munjal University, Gurugram",
  "K.R. Mangalam University, Gurugram",
  "J.C. Bose University of Science and Technology (YMCA Faridabad)",
  "Deenbandhu Chhotu Ram University of Science and Technology (DCRUST Murthal)",
  "Guru Jambheshwar University of Science and Technology (GJUST Hisar)",
  "Harcourt Butler Technical University (HBTU Kanpur)",
  "Madan Mohan Malaviya University of Technology (MMMUT Gorakhpur)",
  "Institute of Engineering and Technology (IET Lucknow)",
  "Kamla Nehru Institute of Technology (KNIT Sultanpur)",
  "Bundelkhand Institute of Engineering & Technology (BIET Jhansi)",
  "Dr. A.P.J. Abdul Kalam Technical University (AKTU Lucknow)",
  "Banaras Hindu University (BHU Varanasi)",
  "Aligarh Muslim University (AMU / Z.H. College of Engineering)",
  "PSIT Kanpur (Pranveer Singh Institute of Technology)",
  "BIT Sindri, Dhanbad",
  "National Institute of Advanced Manufacturing Technology (NIAMT Ranchi)",
  "Muzaffarpur Institute of Technology (MIT Muzaffarpur)",
  "Bhagalpur College of Engineering (BCE Bhagalpur)",
  "Bakhtiyarpur College of Engineering, Patna",
  "Gaya College of Engineering (GCE Gaya)",
  "Darbhanga College of Engineering (DCE Darbhanga)",
  "Motihari College of Engineering (MCE Motihari)",
  "Heritage Institute of Technology, Kolkata",
  "Institute of Engineering and Management (IEM Kolkata)",
  "Techno Main Salt Lake, Kolkata",
  "Techno India University, Kolkata",
  "Kalyani Government Engineering College (KGEC Kalyani)",
  "Jalpaiguri Government Engineering College (JGEC Jalpaiguri)",
  "Haldia Institute of Technology (HIT Haldia)",
  "Netaji Subhash Engineering College (NSEC Kolkata)",
  "Meghnad Saha Institute of Technology (MSIT Kolkata)",
  "St. Thomas' College of Engineering and Technology, Kolkata",
  "Narula Institute of Technology, Agarpara",
  "RCC Institute of Information Technology (RCCIIT Kolkata)",
  "University of Calcutta (Rajabazar Science College)",
  "Pimpri Chinchwad College of Engineering (PCCOE Pune)",
  "MKSSS's Cummins College of Engineering for Women, Pune",
  "MIT World Peace University (MIT-WPU Pune)",
  "Symbiosis Institute of Technology (SIT Pune)",
  "Mukesh Patel School of Technology Management & Engineering (NMIMS Mumbai)",
  "Dwarkadas J. Sanghvi College of Engineering (DJSCE Mumbai)",
  "Thadomal Shahani Engineering College (TSEC Mumbai)",
  "K. J. Somaiya College of Engineering (KJSCE Mumbai)",
  "Fr. Conceicao Rodrigues College of Engineering (CRCE Bandra)",
  "Government College of Engineering, Amravati",
  "Government College of Engineering, Aurangabad",
  "Dr. Babasaheb Ambedkar Technological University (DBATU Lonere)",
  "Chaitanya Bharathi Institute of Technology (CBIT Hyderabad)",
  "Vasavi College of Engineering, Hyderabad",
  "VNR Vignana Jyothi Institute of Engineering and Technology (VNR VJIET Hyderabad)",
  "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET Hyderabad)",
  "BVRIT Hyderabad College of Engineering for Women",
  "JNTUH University College of Engineering Science & Technology, Hyderabad",
  "University College of Engineering, Osmania University, Hyderabad",
  "Mahindra University, Hyderabad",
  "Anurag University, Hyderabad",
  "Vardhaman College of Engineering, Hyderabad",
  "CVR College of Engineering, Hyderabad",
  "Institute of Aeronautical Engineering (IARE Hyderabad)",
  "Keshav Memorial Institute of Technology (KMIT Hyderabad)",
  "K L University (Koneru Lakshmaiah Education Foundation, Guntur / Hyderabad)",
  "Vignan's Foundation for Science, Technology and Research (VFSTR Guntur)",
  "Gayatri Vidya Parishad College of Engineering (GVPCE Visakhapatnam)",
  "Andhra University College of Engineering (AUCE Visakhapatnam)",
  "Sri Venkateswara University College of Engineering (SVUCE Tirupati)",
  "Mohan Babu University (Sree Vidyanikethan, Tirupati)",
  "Velagapudi Ramakrishna Siddhartha Engineering College (VRSEC Vijayawada)",
  "RVR & JC College of Engineering, Guntur",
  "Kumaraguru College of Technology (KCT Coimbatore)",
  "Bannari Amman Institute of Technology, Sathyamangalam",
  "Karunya Institute of Technology and Sciences, Coimbatore",
  "Sri Krishna College of Engineering and Technology (SKCET Coimbatore)",
  "Rajalakshmi Engineering College (REC Chennai)",
  "Sona College of Technology, Salem",
  "College of Engineering, Trivandrum (CET Thiruvananthapuram)",
  "Government Engineering College, Thrissur (GEC Thrissur)",
  "Government Engineering College, Barton Hill",
  "Govt Model Engineering College (MEC Kochi)",
  "TKM College of Engineering, Kollam",
  "Cochin University of Science and Technology (CUSAT Kochi)",
  "Rajagiri School of Engineering & Technology (RSET Kochi)",
  "Mar Athanasius College of Engineering (MACE Kothamangalam)",
  "Muthoot Institute of Technology and Science (MITS Ernakulam)",
  "SCMS School of Engineering and Technology, Ernakulam",
  "Federal Institute of Science and Technology (FISAT Angamaly)",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT Gandhinagar)",
  "Nirma University (Institute of Technology), Ahmedabad",
  "Pandit Deendayal Energy University (PDEU Gandhinagar)",
  "L.D. College of Engineering (LDCE Ahmedabad)",
  "Vishwakarma Government Engineering College (VGEC Chandkheda)",
  "Maharaja Sayajirao University of Baroda (MSU Baroda)",
  "Birla Vishvakarma Mahavidyalaya (BVM Anand)",
  "Dharmsinh Desai University (DDU Nadiad)",
  "Charotar University of Science and Technology (CHARUSAT Changa)",
  "Parul University, Vadodara",
  "Marwadi University, Rajkot",
  "Silver Oak University, Ahmedabad",
  "The LNM Institute of Information Technology (LNMIIT Jaipur)",
  "JECRC University / JECRC Foundation, Jaipur",
  "Poornima University / Poornima College of Engineering, Jaipur",
  "Swami Keshvanand Institute of Technology (SKIT Jaipur)",
  "College of Technology and Engineering (CTAE Udaipur)",
  "MBM University, Jodhpur",
  "Government Engineering College, Ajmer",
  "Shri Govindram Seksaria Institute of Technology and Science (SGSITS Indore)",
  "Institute of Engineering and Technology, DAVV (IET DAVV Indore)",
  "Jabalpur Engineering College (JEC Jabalpur)",
  "Madhav Institute of Technology & Science (MITS Gwalior)",
  "Lakshmi Narain College of Technology (LNCT Bhopal)",
  "Oriental Institute of Science & Technology (OIST Bhopal)",
  "Samrat Ashok Technological Institute (SATI Vidisha)",
  "Medi-Caps University, Indore",
  "University Institute of Engineering and Technology (UIET Panjab University, Chandigarh)",
  "Guru Nanak Dev Engineering College (GNDEC Ludhiana)",
  "Chitkara University (Punjab / Himachal Pradesh)",
  "Chandigarh University, Mohali",
  "Lovely Professional University (LPU Jalandhar)",
  "Sant Longowal Institute of Engineering and Technology (SLIET Punjab)",
  "University of Petroleum and Energy Studies (UPES Dehradun)",
  "Graphic Era Deemed to be University, Dehradun",
  "DIT University, Dehradun",
  "Govind Ballabh Pant University of Agriculture and Technology, Pantnagar",
  "Jaypee University of Information Technology (JUIT Waknaghat)",
  "Assam Engineering College (AEC Guwahati)",
  "Jorhat Engineering College (JEC Jorhat)",
  "Tezpur University (School of Engineering, Napaam)",
  "North Eastern Regional Institute of Science and Technology (NERIST Itanagar)",
  "Sikkim Manipal Institute of Technology (SMIT Majitar)",
  "Goa College of Engineering (GEC Farmagudi)",
  "Padre Conceicao College of Engineering (PCCE Verna, Goa)",
  "Don Bosco College of Engineering, Fatorda, Goa",
  "Government College of Engineering and Technology (GCET Jammu)",
  "Shri Mata Vaishno Devi University (SMVDU Katra)",
  "Islamic University of Science and Technology (IUST Kashmir)",
  "Andhra University College of Engineering (AU Vizag)",
  "JNTU College of Engineering, Kakinada (JNTUK)",
  "JNTU College of Engineering, Anantapur (JNTUA)",
  "JNTU College of Engineering, Pulivendula",
  "JNTU College of Engineering, Vizianagaram",
  "GITAM Deemed to be University, Visakhapatnam",
  "Koneru Lakshmaiah Education Foundation (KL University, Guntur)",
  "Gayatri Vidya Parishad College of Engineering (GVPCE Vizag)",
  "Vignan's Foundation for Science, Technology & Research (VFSTR Vadlamudi, Guntur)",
  "GMR Institute of Technology (GMRIT Rajam)",
  "Sree Vidyanikethan Engineering College (SVEC Tirupati / Mohan Babu University)",
  "Prasad V. Potluri Siddhartha Institute of Technology (PVPSIT Vijayawada)",
  "MVGR College of Engineering, Vizianagaram",
  "Aditya Engineering College, Surampalem",
  "Aditya College of Engineering and Technology, Surampalem",
  "Vasireddy Venkatadri Institute of Technology (VVIT Guntur)",
  "Vishnu Institute of Technology, Bhimavaram",
  "Shri Vishnu Engineering College for Women (SVECW Bhimavaram)",
  "Sagi Rama Krishnam Raju Engineering College (SRKR Bhimavaram)",
  "Bapatla Engineering College (BEC Bapatla)",
  "Madanapalle Institute of Technology & Science (MITS Madanapalle)",
  "Sreenivasa Institute of Technology and Management Studies (SITAMS Chittoor)",
  "G. Pulla Reddy Engineering College (GPREC Kurnool)",
  "JNTUA College of Engineering, Kalikiri",
  "Rajeev Gandhi Memorial College of Engineering and Technology (RGMCET Nandyal)",
  "Annamacharya Institute of Technology & Sciences (AITS Rajampet)",
  "Dhanekula Institute of Engineering and Technology, Vijayawada",
  "G. Narayanamma Institute of Technology and Science (GNITS Hyderabad for Women)",
  "Anurag University / Anurag Group of Institutions, Hyderabad",
  "Mahatma Gandhi Institute of Technology (MGIT Hyderabad)",
  "BVRIT Narsapur (B.V. Raju Institute of Technology, Medak)",
  "Sreenidhi Institute of Science and Technology (SNIST Hyderabad)",
  "MLR Institute of Technology (MLRIT Hyderabad)",
  "Kakatiya Institute of Technology and Science (KITS Warangal)",
  "Guru Nanak Institutions Technical Campus (GNITC Hyderabad)",
  "CMR College of Engineering & Technology (CMRCET Hyderabad)",
  "CMR Institute of Technology (CMRIT Hyderabad)",
  "CMR Technical Campus (CMRT Hyderabad)",
  "Malla Reddy Engineering College (MREC Hyderabad)",
  "Malla Reddy College of Engineering and Technology (MRCET Hyderabad)",
  "Neil Gogte Institute of Technology (NGIT Hyderabad)",
  "Mahindra University (École Centrale School of Engineering, Hyderabad)",
  "Woxsen University (School of Technology, Hyderabad)",
  "Geethanjali College of Engineering and Technology (GCET Hyderabad)",
  "Matrusri Engineering College, Hyderabad",
  "Maturi Venkata Subba Rao Engineering College (MVSR Hyderabad)",
  "Kakatiya University College of Engineering and Technology, Kothagudem",
  "JNTUH College of Engineering, Manthani",
  "JNTUH College of Engineering, Sultanpur",
  "JNTUH College of Engineering, Rajanna Sircilla",
  "Anna University (College of Engineering, Guindy - CEG Chennai)",
  "Madras Institute of Technology (MIT Chromepet, Anna University)",
  "Alagappa Chettiar Government College of Engineering and Technology (ACGCET Karaikudi)",
  "Government College of Engineering, Salem (GCE Salem)",
  "Government College of Engineering, Tirunelveli (GCE Tirunelveli)",
  "Government College of Technology, Coimbatore (GCT Coimbatore)",
  "Government College of Engineering, Bargur",
  "Government College of Engineering, Thanjavur",
  "Government College of Engineering, Bodinayakkanur",
  "Government College of Engineering, Dharmapuri",
  "Coimbatore Institute of Technology (CIT Coimbatore)",
  "PSG Institute of Advanced Studies, Coimbatore",
  "Sri Sivasubramaniya Nadar College of Engineering (SSN Chennai)",
  "Sri Krishna College of Technology (SKCT Coimbatore)",
  "Sri Sairam Engineering College, Chennai",
  "Sri Sairam Institute of Technology, Chennai",
  "St. Joseph's College of Engineering, Chennai",
  "St. Joseph's Institute of Technology, Chennai",
  "R.M.K. Engineering College, Thiruvallur",
  "R.M.D. Engineering College, Thiruvallur",
  "Meenakshi Sundararajan Engineering College, Chennai",
  "Easwari Engineering College (SRM Group, Ramapuram)",
  "Panimalar Engineering College, Chennai",
  "Saveetha Engineering College, Chennai",
  "Velammal Engineering College, Chennai",
  "Velammal Institute of Technology, Chennai",
  "KPR Institute of Engineering and Technology (KPRIET Coimbatore)",
  "National Engineering College (NEC Kovilpatti)",
  "Mepco Schlenk Engineering College, Sivakasi",
  "Kongu Engineering College, Perundurai (Erode)",
  "K.S. Rangasamy College of Technology (KSRCT Tiruchengode)",
  "Dr. Mahalingam College of Engineering and Technology (MCET Pollachi)",
  "Hindusthan College of Engineering and Technology (HICET Coimbatore)",
  "Hindustan Institute of Technology and Science (HITS Padur, Chennai)",
  "BS Abdur Rahman Crescent Institute of Science and Technology, Chennai",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology, Chennai",
  "Sathyabama Institute of Science and Technology, Chennai",
  "Vels Institute of Science, Technology & Advanced Studies (VISTAS Chennai)",
  "Kalasalingam Academy of Research and Education (KARE Krishnankoil)",
  "Ramaiah Institute of Technology (MSRIT Bangalore)",
  "KLE Technological University (B.V. Bhoomaraddi College, Hubballi)",
  "SDM College of Engineering and Technology (SDMCET Dharwad)",
  "NMAM Institute of Technology (NMAMIT Nitte)",
  "R.N.S. Institute of Technology (RNSIT Bangalore)",
  "B.N.M. Institute of Technology (BNMIT Bangalore)",
  "Presidency University, Bangalore",
  "Alliance University (Alliance College of Engineering and Design, Bangalore)",
  "Jain University (Faculty of Engineering and Technology - JU FET Bangalore)",
  "Dayananda Sagar Academy of Technology and Management (DSATM Bangalore)",
  "Global Academy of Technology (GAT Bangalore)",
  "Acharya Institute of Technology, Bangalore",
  "The Oxford College of Engineering, Bangalore",
  "East West Institute of Technology (EWIT Bangalore)",
  "MVJ College of Engineering, Bangalore",
  "Don Bosco Institute of Technology (DBIT Bangalore)",
  "Dr. Ambedkar Institute of Technology (Dr. AIT Bangalore)",
  "GSSS Institute of Engineering and Technology for Women (GSSSIETW Mysore)",
  "Malnad College of Engineering (MCE Hassan)",
  "Bapuji Institute of Engineering and Technology (BIET Davangere)",
  "University BDT College of Engineering (UBDTCE Davangere)",
  "Basaveshwar Engineering College (BEC Bagalkot)",
  "KLS Gogte Institute of Technology (GIT Belagavi)",
  "Sahyadri College of Engineering & Management, Mangalore",
  "St Joseph Engineering College (SJEC Vamanjoor, Mangalore)",
  "Canara Engineering College, Mangalore",
  "Sardar Patel College of Engineering (SPCE Mumbai)",
  "Institute of Chemical Technology (ICT Mumbai)",
  "Vishwakarma Institute of Information Technology (VIIT Pune)",
  "Government College of Engineering, Karad",
  "Government College of Engineering, Chandrapur",
  "Government College of Engineering, Jalgaon",
  "Government College of Engineering, Yavatmal",
  "Shri Guru Gobind Singhji Institute of Engineering and Technology (SGGSIE&T Nanded)",
  "Ramrao Adik Institute of Technology (RAIT Navi Mumbai)",
  "D.Y. Patil College of Engineering, Akurdi (Pune)",
  "D.Y. Patil Institute of Technology, Pimpri (Pune)",
  "MIT Academy of Engineering (MITAOE Alandi, Pune)",
  "Bharati Vidyapeeth Deemed University College of Engineering (BVDUCOE Pune)",
  "Sinhgad College of Engineering (SCOE Vadgaon, Pune)",
  "Smt. Kashibai Navale College of Engineering (SKNCOE Pune)",
  "P.E.S. Modern College of Engineering, Pune",
  "Vidyalankar Institute of Technology (VIT Wadala, Mumbai)",
  "Xavier Institute of Engineering, Mahim (Mumbai)",
  "Shah and Anchor Kutchhi Engineering College (SAKEC Chembur, Mumbai)",
  "Atharva College of Engineering, Malad (Mumbai)",
  "Don Bosco Institute of Technology (DBIT Kurla, Mumbai)",
  "Thakur College of Engineering and Technology (TCET Kandivali, Mumbai)",
  "Rajiv Gandhi Institute of Technology (RGIT Andheri, Mumbai)",
  "Fr. Conceicao Rodrigues Institute of Technology (FCRIT Vashi, Navi Mumbai)",
  "Shri Ramdeobaba College of Engineering and Management (RCOEM Nagpur)",
  "Yeshwantrao Chavan College of Engineering (YCCE Nagpur)",
  "Government College of Engineering, Nagpur (GCOEN)",
  "G.H. Raisoni College of Engineering (GHRCE Nagpur)",
  "K.K. Wagh Institute of Engineering Education and Research (KKWIEER Nashik)",
  "Sandip Foundation / Sandip University, Nashik",
  "MET League of Colleges (Institute of Engineering, Nashik)",
  "Rajkiya Engineering College (REC Banda)",
  "Rajkiya Engineering College (REC Bijnor)",
  "Rajkiya Engineering College (REC Azamgarh)",
  "Rajkiya Engineering College (REC Kannauj)",
  "Rajkiya Engineering College (REC Mainpuri)",
  "Rajkiya Engineering College (REC Sonbhadra)",
  "JSS Academy of Technical Education (JSSATE Noida)",
  "KIET Group of Institutions (Krishna Institute of Engineering and Technology, Ghaziabad)",
  "ABES Institute of Technology (ABESIT Ghaziabad)",
  "GL Bajaj Institute of Technology and Management (GLBITM Greater Noida)",
  "Noida Institute of Engineering and Technology (NIET Greater Noida)",
  "IMS Engineering College (IMSEC Ghaziabad)",
  "GLA University, Mathura",
  "Invertis University, Bareilly",
  "Shri Ramswaroop Memorial University (SRMU Lucknow)",
  "Babu Banarasi Das Northern India Institute of Technology (BBDNIIT Lucknow)",
  "United College of Engineering and Research (UCER Prayagraj / Naini)",
  "Pranveer Singh Institute of Technology (PSIT Kanpur)",
  "Techno Main Salt Lake (Techno India Group, Kolkata)",
  "Techno International New Town, Kolkata",
  "University of Engineering & Management (UEM Kolkata)",
  "Dr. B.C. Roy Engineering College (BCREC Durgapur)",
  "Asansol Engineering College (AEC Asansol)",
  "Government College of Engineering and Leather Technology (GCELT Kolkata)",
  "Government College of Engineering and Ceramic Technology (GCECT Kolkata)",
  "Government College of Engineering and Textile Technology (GCETTB Berhampore)",
  "Government College of Engineering and Textile Technology (GCETTS Serampore)",
  "Narula Institute of Technology (NIT Agarpara, Kolkata)",
  "Guru Nanak Institute of Technology (GNIT Kolkata)",
  "JIS College of Engineering, Kalyani",
  "MCKV Institute of Engineering, Howrah",
  "Future Institute of Engineering and Management (FIEM Sonarpur, Kolkata)",
  "Netaji Subhash Engineering College (NSEC Garia, Kolkata)",
  "Nalanda College of Engineering, Chandi",
  "Loknayak Jai Prakash Institute of Technology (LNJPIT Chapra)",
  "Saharsa College of Engineering, Saharsa",
  "Purnea College of Engineering, Purnea",
  "Supaul College of Engineering, Supaul",
  "Katihar Engineering College, Katihar",
  "Shershah Engineering College, Sasaram",
  "Rashtrakavi Ramdhari Singh Dinkar College of Engineering, Begusarai",
  "Government Engineering College, Vaishali",
  "Government Engineering College, Samastipur",
  "Government Engineering College, Banka",
  "Government Engineering College, Gopalganj",
  "Government Engineering College, Madhubani",
  "Government Engineering College, Siwan",
  "Government Engineering College, Jamui",
  "Government Engineering College, Nawada",
  "Government Engineering College, Aurangabad (Bihar)",
  "Government Engineering College, Buxar",
  "Government Engineering College, Bhojpur (Ara)",
  "Cambridge Institute of Technology (CIT Tatisilwai, Ranchi)",
  "Veer Surendra Sai University of Technology (VSSUT Burla / UCE Burla)",
  "Kalinga Institute of Industrial Technology (KIIT Deemed to be University, Bhubaneswar)",
  "Government College of Engineering, Kalahandi (GCEK Bhawanipatna)",
  "National Institute of Science and Technology (NIST Autonomous, Berhampur)",
  "Gandhi Institute of Engineering and Technology University (GIET University, Gunupur)",
  "International Institute of Information Technology Bhubaneswar (IIIT Bhubaneswar)",
  "Indira Gandhi Institute of Technology (IGIT Sarang, Dhenkanal)",
  "College of Engineering and Technology (CET Bhubaneswar)",
  "Roland Institute of Technology, Berhampur",
  "Seemanta Engineering College, Mayurbhanj",
  "Majhighariani Institute of Technology and Science (MITS Rayagada)",
  "Chandigarh College of Engineering and Technology (CCET Chandigarh)",
  "Chandigarh University, Mohali (Gharuan)",
  "Lovely Professional University (LPU Phagwara / Jalandhar)",
  "Sant Longowal Institute of Engineering and Technology (SLIET Longowal)",
  "J.C. Bose University of Science and Technology, YMCA (Faridabad)",
  "University Institute of Engineering and Technology (UIET MDU Rohtak)",
  "University Institute of Engineering and Technology (UIET Kurukshetra University)",
  "Manav Rachna International Institute of Research and Studies (MRIIRS Faridabad)",
  "GD Goenka University, Gurugram",
  "Amity University, Gurugram (Manesar)",
  "Graphic Era Hill University (Dehradun / Bhimtal)",
  "Govind Ballabh Pant Institute of Engineering and Technology (GBPIET Pauri Garhwal)",
  "Bipin Tripathi Kumaon Institute of Technology (BTKIT Dwarahat)",
  "College of Technology, Pantnagar (GBPUAT)",
  "THDC Institute of Hydropower Engineering and Technology (THDC-IHET Tehri)",
  "Jaypee University of Information Technology (JUIT Waknaghat, Solan)",
  "University Institute of Technology, Himachal Pradesh University (UIIT HPU Shimla)",
  "Jawaharlal Nehru Government Engineering College (JNGEC Sundernagar, Mandi)",
  "Atal Bihari Vajpayee Government Institute of Engineering and Technology (ABVGIE&T Pragatinagar, Shimla)",
  "Rajiv Gandhi Government Engineering College (RGGEC Kangra)",
  "Birla Institute of Technology and Science (BITS Pilani)",
  "MBM University, Jodhpur (MBM Engineering College)",
  "Rajasthan Technical University (RTU Kota / UCE Kota)",
  "Government Engineering College, Ajmer (ECA)",
  "Government Engineering College, Bikaner (ECB)",
  "Government Engineering College, Bharatpur",
  "Government Engineering College, Jhalawar",
  "Government Women Engineering College, Ajmer (GWEC Ajmer)",
  "Poornima College of Engineering / Poornima University, Jaipur",
  "Arya College of Engineering and IT (ACEIT Jaipur)",
  "Banasthali Vidyapith, Niwai (Tonk)",
  "Government Engineering College, Surat (GEC Surat)",
  "Government Engineering College, Rajkot (GEC Rajkot)",
  "Government Engineering College, Gandhinagar (GEC Gandhinagar)",
  "Government Engineering College, Bhavnagar (GEC Bhavnagar)",
  "Government Engineering College, Bhuj (GEC Bhuj)",
  "Government Engineering College, Modasa (GEC Modasa)",
  "Indus University, Ahmedabad",
  "Ahmedabad University (School of Engineering and Applied Science)",
  "Ganpat University (U.V. Patel College of Engineering, Mehsana)",
  "Rewa Engineering College (REC Rewa)",
  "Ujjain Engineering College (UEC Ujjain)",
  "Indira Gandhi Engineering College (IGEC Sagar)",
  "University Institute of Technology, RGPV (UIT RGPV Bhopal)",
  "Sagar Institute of Science and Technology (SISTec Bhopal)",
  "Technocrats Institute of Technology (TIT Bhopal)",
  "Acropolis Institute of Technology and Research (AITR Indore)",
  "Prestige Institute of Engineering Management & Research, Indore",
  "Government Engineering College, Barton Hill (Thiruvananthapuram)",
  "Government Engineering College, Kozhikode (GEC Kozhikode)",
  "Government Engineering College, Palakkad (GEC Sreekrishnapuram)",
  "Government Engineering College, Kannur (GEC Kannur)",
  "Government Engineering College, Idukki (GEC Painavu)",
  "Government Engineering College, Wayanad (GEC Mananthavady)",
  "Govt Model Engineering College (MEC Thrikkakara, Kochi)",
  "Rajagiri School of Engineering & Technology (RSET Kakkanad, Kochi)",
  "SCMS School of Engineering and Technology, Karukutty",
  "Muthoot Institute of Technology and Science (MITS Varikoli)",
  "Saintgits College of Engineering, Kottayam",
  "Amal Jyothi College of Engineering, Kanjirappally",
  "Mar Baselios College of Engineering and Technology (MBCET Thiruvananthapuram)",
  "Marian Engineering College, Kazhakuttam",
  "LBS Institute of Technology for Women (LBSITW Poojappura, Thiruvananthapuram)",
  "LBS College of Engineering, Kasaragod",
  "NSS College of Engineering, Palakkad",
  "Goa College of Engineering (GEC Farmagudi, Ponda)",
  "Padre Conceicao College of Engineering (PCCE Verna, Salcete, Goa)",
  "Don Bosco College of Engineering (DBCE Fatorda, Margao, Goa)",
  "Agnel Institute of Technology and Design (AITD Assagao, Bardez, Goa)",
  "Government College of Engineering and Technology (GCET Safapora, Ganderbal, Kashmir)",
  "Islamic University of Science and Technology (IUST Awantipora, Kashmir)",
  "Baba Ghulam Shah Badshah University (BGSBU Rajouri)",
  "Model Institute of Engineering and Technology (MIET Jammu)",
  "SSM College of Engineering, Pattan (Baramulla, Kashmir)",
  "Assam Engineering College (AEC Jalukbari, Guwahati)",
  "Jorhat Institute of Science and Technology (JIST Jorhat)",
  "Bineswar Brahma Engineering College (BBEC Kokrajhar)",
  "Barak Valley Engineering College (BVEC Karimganj)",
  "Dhemaji Engineering College (DEC Dhemaji)",
  "Golaghat Engineering College (GEC Golaghat)",
  "Tezpur University (School of Engineering, Assam)",
  "North Eastern Regional Institute of Science and Technology (NERIST Nirjuli, Itanagar)",
  "Tripura Institute of Technology (TIT Narsingarh, Agartala)",
  "Sikkim Manipal Institute of Technology (SMIT Majitar, Rangpo)"
];

export const PROGRAMMING_LANGUAGES: string[] = [
  "C++",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Go",
  "Rust",
  "C",
  "C#",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "SQL",
  "Dart",
  "Scala",
  "R",
  "HTML / CSS",
  "Bash / Shell",
  "Lua",
  "Haskell",
  "Elixir",
  "Clojure",
  "Perl",
  "Julia",
  "Solidity",
  "Assembly",
  "MATLAB",
  "Zig",
  "OCaml",
  "Groovy",
];

export const POPULAR_LANGUAGES: string[] = [
  "C++",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Go",
  "Rust",
  "SQL",
  "Kotlin",
  "Swift",
];

// Master Backend, Frontend & Tech Stack
export const TECH_STACK_OPTIONS: string[] = [
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Django",
  "FastAPI",
  "Flask",
  "Spring Boot",
  "ASP.NET Core",
  "Ruby on Rails",
  "Laravel",
  "Docker",
  "Kubernetes",
  "AWS",
  "Microsoft Azure",
  "Google Cloud (GCP)",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Redis",
  "Prisma",
  "Supabase",
  "Firebase",
  "GraphQL",
  "gRPC",
  "Apache Kafka",
  "RabbitMQ",
  "Elasticsearch",
  "Tailwind CSS",
  "Linux",
  "Nginx",
  "Git & GitHub",
  "GitHub Actions",
  "Terraform",
  "Flutter",
  "React Native",
  "Android",
  "iOS",
  "WebSockets",
  "tRPC",
  "Microservices",
  "Electron",
];

export const POPULAR_TECH_STACK: string[] = [
  "Next.js",
  "React",
  "Node.js",
  "Docker",
  "PostgreSQL",
  "AWS",
  "Redis",
  "Kubernetes",
  "MongoDB",
  "Express.js",
  "Tailwind CSS",
  "Spring Boot",
];

// Master Computer Science Concepts
export const CS_CONCEPTS_OPTIONS: string[] = [
  "Data Structures & Algorithms (DSA)",
  "System Design",
  "Object-Oriented Programming (OOP)",
  "Database Management Systems (DBMS)",
  "Operating Systems (OS)",
  "Computer Networks (CN)",
  "Low-Level Design (LLD)",
  "High-Level Design (HLD)",
  "Microservices Architecture",
  "Distributed Systems",
  "RESTful APIs",
  "GraphQL APIs",
  "Machine Learning (ML)",
  "Deep Learning (DL)",
  "Artificial Intelligence (AI)",
  "Generative AI & LLMs",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Cloud Computing",
  "DevOps & CI/CD",
  "Cybersecurity & Cryptography",
  "Competitive Programming",
  "Web3 & Blockchain",
  "Software Testing & QA",
  "Agile & Scrum Methodologies",
];

export const POPULAR_CONCEPTS: string[] = [
  "Data Structures & Algorithms (DSA)",
  "System Design",
  "Object-Oriented Programming (OOP)",
  "DBMS",
  "Operating Systems (OS)",
  "Computer Networks (CN)",
  "Microservices",
  "Distributed Systems",
  "Machine Learning (ML)",
  "RESTful APIs",
];
